#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if [ -z "${2}" ]; then
            deb-systemd-helper disable iperf3.service >/dev/null || true
            deb-systemd-invoke stop iperf3.service >/dev/null || true
        fi

        # Activate package triggers.
        dpkg-trigger update-workbench

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.iperf3"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.iperf3" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
